import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/header";
import Foooter from "@/components/layout/footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { UserContex, UserProvider } from "./context/user-context";
import { useContext, useEffect } from "react";
import { ProductProvider } from "../../src/app/context/product-context";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const handler = () => {
//   alert("sainuu");
// };
// type TProps = {
//   children: React.ReactNode
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProductProvider>
          <UserProvider>
            <Header />
            {children}
            <Foooter />
            <ToastContainer />
          </UserProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
